import { FreqClueDifficulty } from '../../types/freq.types'
import { LanguageCode } from '../../types/game.types'

type FreqCluePair = string[]

const FREQ_CLUES: Record<
  LanguageCode,
  Record<FreqClueDifficulty, FreqCluePair[]>
> = {
  en: {
    easy: [
      ['Sustenance', 'Haute Cuisine'],
      ['Soft', 'Hard'],
      ['Ineffective', 'Effective'],
      ['Bad Superpower', 'Good Superpower'],
      ['Unhealthy', 'Healthy'],
      ['Bad Man', 'Good Man'],
      ['Unbelievable', 'Believable'],
      ['Underrated Movie', 'Overrated Movie'],
      ['Unknown', 'Famous'],
      ['Easy Subject', 'Hard Subject'],
      ['Friend', 'Enemy'],
      ['Unpopular', 'Popular'],
      ['Boring', 'Exciting'],
      ['Smelly In A Bad Way', 'Smelly In A Good Way'],
      ['Fad', 'Classic'],
      ['Useless Body Part', 'Useful Body Part'],
      ['Unfashionable', 'Fashionable'],
      ['Freedom Fighter', 'Terrorist'],
      ['Tastes Bad', 'Tastes Good'],
      ['Sport', 'Game'],
      ['Unimportant', 'Important'],
      ['Easy To Spell', 'Hard To Spell'],
      ['Weak', 'Strong'],
      ['Disgusting Cereal', 'Delicious Cereal'],
      ['Hard To Remember', 'Easy To Remember'],
      ['Lowbrow', 'Highbrow'],
      ['Job ', 'Career'],
      ['Happens Slowly', 'Happens Suddenly'],
      ['Movie', 'Film'],
      ['Ethical To Eat', 'Unethical To Eat'],
      ['Worst Athlete Of All Time', 'Greatest Athlete Of All Time'],
      ['Replaceable', 'Irreplaceable'],
      ['Good', 'Evil'],
      ['Worst Day Of The Year', 'Best Day Of The Year'],
      ['Hairless', 'Hairy'],
      ['Historically Important', 'Historically Unimportant'],
      ['Dry Food', 'Wet Food'],
      ['Need', 'Want'],
      ['Vice', 'Virtue'],
      ['Underrated Musician', 'Overrated Musician'],
      ['Uncontroversial Topic', 'Controversial Topic'],
      ['Mental Activity', 'Physical Activity'],
      ['Unethical', 'Ethical'],
      ['Boring Hobby', 'Interesting Hobby'],
      ['Mean Person', 'Nice Person'],
      ['Action Movie', 'Adventure Movie'],
      ['Rare', 'Common'],
      ['Unsexy Emoji', 'Sexy Emoji'],
      ['Underrated Skill', 'Overrated Skill'],
      ['Dry', 'Wet'],
      ['Normal Pet', 'Exotic Pet'],
      ['Inflexible', 'Flexible'],
      ['Artisinal', 'Mass Produced'],
      ['Stupid', 'Brilliant'],
      ['Ugly Man', 'Beautiful Man'],
      ['Hard To Find', 'Easy To Find'],
      ['Wise', 'Intelligent'],
      ['Hart To Do', 'Easy To Do'],
      ['Bad TV Show', 'Good TV Show'],
      ['Traditionally Masculine', 'Tradtionally Feminine'],
      ['Liberal ', 'Conservative'],
      ['Useless Invention', 'Useful Invention'],
      ['Not A Sandwich', 'A Sandwich'],
      ['Poorly Made', 'Well Made'],
      ['Messy Food', 'Clean Food'],
      ['Underrated ', 'Overrated'],
      ['Worst Living Person', 'Greatest Living Person'],
      ['Uncool', 'Cool'],
      ['Sad Movie', 'Happy Movie'],
      ['Waste Of Time', 'Good Use Of Time'],
      ['Dark', 'Light'],
      ['Underrated Actor', 'Overrated Actor'],
      ['Plain', 'Fancy'],
      ['Has A Bad Reputation', 'Has A Good Reputation'],
      ['Bad', 'Good'],
      ['Milly Addictive', 'Highly Addictive'],
      ['Unsexy Animal', 'Sexy Animal'],
      ['Low Quality', 'High Quality'],
      ['Straight', 'Curvy'],
      ['Normal Thing To Own', 'Weird Thing To Own'],
      ['Underpaid', 'Overpaid'],
      ['Casual', 'Formal'],
      ['Looks Like A Person', 'Doesn’t Look Like A Person'],
      ['Temporary', 'Permanent'],
      ['Easy To Kill', 'Hard To Kill'],
      ['Unreliable', 'Reliable'],
      ['Bad Music', 'Good Music'],
      ['Unhygienic', 'Hygienic'],
      ['Proof That God Exists', 'Proof That God Doesn’t Exist'],
      ['Round', 'Pointy'],
      ['Fragile', 'Durable'],
      ['Geek', 'Dork'],
      ['Basic', 'Hipster'],
      ['Bad Actor', 'Good Actor'],
      ['Unpopular Activity', 'Popular Activity'],
      ['Divided', 'Whole'],
      ['Underrated Weapon', 'Overrated Weapon'],
      ['Cheap', 'Expensive'],
      ['Introvert', 'Extrovert'],
      ['Book Was Better', 'Movie Was Better'],
      ['Harmless', 'Harmful'],
      ['Gryffindor', 'Slytherin'],
      ['Difficult To Use', 'Easy To Use'],
      ['Tired', 'Wired'],
      ['Nobody Does It', 'Everybody Does It'],
      ['Short Lived', 'Long Lived'],
      ['Loved', 'Hated'],
      ['The Light Side Of The Force', 'The Dark Side Of The Force'],
      ['Bad Pizza Topping', 'Good Pizza Topping'],
      ['Dystopia', 'Utopia'],
      ['Bad Movie', 'Good Movie'],
      ['Ugly', 'Beautiful'],
      ['Better Hot', 'Better Cold'],
      ['Square', 'Round'],
      ['Hot', 'Cold'],
      ['Normal', 'Weird'],
      ['Feels Bad', 'Feels Good'],
      ['Inessential', 'Essential'],
      ['Underrated Thing To Do', 'Overrated Thing To Do'],
      ['Villain', 'Hero'],
      ['Mature Person', 'Immature Person'],
      ['Underrate Thing To Own', 'Overrated Thing To Own'],
      ['Hard To Pronounce', 'Easy To Pronounce'],
      ['Ordinary', 'Extraordinary'],
      ['Scary Animal', 'Nice Animal'],
      ['Mainstream', 'Niche'],
      ['Scary Animal', 'Nice Animal'],
      ['Requires Luck', 'Requires Skill'],
      ['Dirty', 'Clean'],
      ['Movie That Godzilla Would Ruin', 'Movie That Godzilla Would Improve'],
      ['Useless', 'Useful'],
      ['Smells Bad', 'Smells Good'],
      ['Star Wars', 'Star Trek'],
      ['Sad Song', 'Happy Song'],
      ['Forbidden', 'Encouraged'],
      ['Optional', 'Mandatory'],
      ['Underrated Letter Of The Alphabet', 'Overrated Letter Of The Alphabet'],
      ['Bad Person', 'Good Person'],
      ['80s', '90s'],
      ['Round Animal', 'Pointy Animal'],
      ['Unstable', 'Stable'],
      ['Dangerous', 'Safe'],
      ['Culturally Significant', 'Culturally Insignificant'],
      ['Untalented', 'Talented'],
      ['Guilty Pleasure', 'Openly Love'],
      ['Cat Person', 'Dog Person'],
      ['Bad Habit', 'Good Habit'],
      ['Boring Topic', 'Fascinating Topic'],
      ['Flavorless', 'Flavorful'],
      ['Low Calorie', 'High Calorie'],
      ['Colorless', 'Colorful'],
      ['Role Model', 'Bad Influence'],
      ['Useless Major', 'Useful Major'],
      ['Dangerous Job', 'Safe Job'],
      ['Fantasy', 'Sci-Fi'],
      ['Comedy', 'Drama'],
      ['Quiet Place', 'Loud Place'],
      ['Bad For You', 'Good For You'],
      ['Rough', 'Smooth'],
      ['Useless In An Emergency', 'Useful In An Emergency'],
      ['For Kids', 'For Adults'],
      ['Nature', 'Nurture'],
      ['Worthless', 'Priceless'],
      ['Snack', 'Meal'],
      ['Least Evil Company', 'Most Evil Company'],
      ['Unforgivable', 'Forigvable'],
    ],
    hard: [
      // Unsure (may be in 'hard' list)
      ['Square', 'Hip'],
      ['Expected', 'Unexpected'],
      ['Sad', 'Happy'],
      ['Person You Could Beat Up', 'Person Who’d Beat You Up'],
      ['Worst Era To Time Travel', 'Best Era To Time Travel'],
      ['Conventional Thinking', 'Fringe Theory'],
      ['Delusional', 'Rational'],
      ['Trashy', 'Classy'],
      ['Not sci-fi', 'Sci-fi'],
      ['Dictatorship', 'Democracy'],
    ],
  },
}

export default FREQ_CLUES
