import { LanguageCode } from '../../types/game.types'

const FREQ_CLUES: Record<LanguageCode, string[][]> = {
  en: [
    ['Cold', 'Hot'],
    ['Square', 'Hip'],
    ['Overrated Movie', 'Underrated Movie'],
    ['Expected', 'Unexpected'],
    ['Overrated Movie', 'Underrated Movie'],
    ['Expected', 'Unexpected'],
    ['Sad', 'Happy'],
    ['Dark', 'Light'],
    ['Person you could beat up', 'Person who’d beat you up'],
    ['Worst era to time travel', 'Best era to time travel'],
    ['Beautiful', 'Ugly'],
    ['Conventional thinking', 'Fringe theory'],
    ['Exciting', 'Boring'],
    ['Delusional', 'Rational'],
    ['Messy food', 'Clean food'],
    ['Worst living person', 'Best living person'],
    ['Role model', 'Bad influence'],
    ['Trashy', 'Classy'],
    ['Unpopular', 'Popular'],
    ['Round', 'Pointy'],
    ['Not sci-fi', 'Sci-fi'],
    ['Lowbrow', 'Highbrow'],
    ['Sci-fi', 'Fantasy'],
    ['Sad song', 'Happy song'],
    ['Job', 'Career'],
    ['Rough', 'Smooth'],
    ['Good', 'Evil'],
    ['Cool', 'Uncool'],
    ['Inflexible', 'Flexible'],
    ['Guilty pleasure', 'Openly love'],
    ['Ugly man', 'Beautiful man'],
    ['Low quality', 'High quality'],
    ['Bad superpower', 'Good superpower'],
    ['Book was better', 'Movie was better'],
    ['Quiet place', 'Loud place'],
    ['Feels bad', 'Feels good'],
    ['Dictatorship', 'Democracy'],
    ['Useless invention', 'Useful invention'],
  ],
}

export default FREQ_CLUES
