export const API_GAME = '/api/games/%0'
export const API_GAME_COMMAND = '/api/games/%0/command'
export const API_GAME_LEAVE = '/api/games/%0/leave'
export const API_GAME_JOIN = '/api/games/%0/join'
export const API_GAME_PHASE = '/api/games/%0/phase'
export const API_LOGIN = '/api/auth/login'
export const API_LOGOUT = '/api/auth/logout'
export const API_USER = '/api/user'

export const DEBUG_MODE_KEY = 'freq/debug-mode'
export const ROOM_KEY = 'freq/room'
export const ROOM_REDIRECT_KEY = 'freq/room-redirect'
export const THEME_KEY = 'freq/theme'
