export const API_GAME = '/api/%0/%1'
export const API_GAME_LEAVE = '/api/%0/%1/leave'
export const API_GAME_JOIN = '/api/%0/%1/join'
export const API_GAME_COMMAND = '/api/%0/%1/command'
export const API_GAME_PHASE = '/api/%0/%1/phase'

export const API_LOGIN = '/api/auth/login'
export const API_LOGOUT = '/api/auth/logout'
export const API_USER = '/api/user'
export const API_USER_ROOMS = '/api/user/rooms'
export const API_USER_AS_USER = '/api/user/as-user'
export const API_ROOM_CODE = '/api/room-code'

export const ROUTE_HOME = '/'
export const ROUTE_GAME_HOME = '/%0'
export const ROUTE_GAME_ROOM = '/%0/%1'

export const KEY_ROOM = 'freq/room'
export const KEY_ROOM_REDIRECT = 'freq/room-redirect'
export const KEY_ROOM_TYPE = 'freq/room-type'
export const KEY_THEME = 'freq/theme'
