import { Dict } from '../../types/object.types'

const CWD_CODE_WORD_BREAKS: Dict<number> = {
  ambulance: 4,
  antarctica: 6,
  astronaut: 5,
  australia: 4,
  avalanche: 4,
  battleship: 6,
  blacksmith: 5,
  butterfly: 3,
  chocolate: 5,
  christmas: 6,
  cleopatra: 4,
  conductor: 6,
  earthquake: 5,
  greenhouse: 5,
  goldilocks: 5,
  halloween: 5,
  hamburger: 3,
  helicopter: 4,
  himalayas: 4,
  hollywood: 5,
  horseshoe: 5,
  jellyfish: 5,
  kangaroo: 4,
  leprechaun: 5,
  lightning: 5,
  limousine: 5,
  lumberjack: 6,
  microscope: 5,
  microwave: 5,
  millionaire: 4,
  musketeer: 4,
  parachute: 4,
  revolution: 4,
  satellite: 5,
  scarecrow: 5,
  scientist: 5,
  shakespeare: 5,
  skyscraper: 3,
  stethoscope: 5,
  superhero: 5,
  telescope: 4,
  undertaker: 5,
  university: 6,
  valentine: 5,
  washington: 4,
  wheelchair: 5,
  wonderland: 4,
  yellowstone: 6,
}

export default CWD_CODE_WORD_BREAKS
